name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan branch utama Anda jika berbeda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js untuk pnpm
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Sesuaikan dengan versi Node.js proyek Anda

    # Install pnpm
    - name: Install pnpm
      run: npm install -g pnpm

    # Install dependencies dengan pnpm
    - name: Install dependencies
      run: pnpm install

    # Build proyek Vite dengan pnpm
    - name: Build project
      run: pnpm run build

    # Deploy ke GitHub Pages menggunakan branch `gh-pages`
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Direktori output build Vite (default: `dist`)
